### ISSUE TITLE
Support shell pipe

### ISSUE THREAD

**Issue by lamnguyenx** [waszil/subpiper#2]
Hi waszil,

This is a really well-done python module. I really admire the way you handle stdout and stderr in real time with callback functions ;)

I'd like to ask if you had any plan to make it support shell piping, with no need to switch to "shell=True"?

Thanks!!

**Comment by waszil** [comment]
Hi, thanks, however I must note that unfortunately we have run into some problems using this for capturing output of several processes parallel, unfortunately it cannot always handle it correctly, so I'd say, this is not a mature package at all, just to be clear. Sorry, but I don't plan on supporting shell piping, but feel free to submit a PR.
